name: qr_code_scanner_example
description: Demonstrates how to use the flutter_qr plugin.
publish_to: 'none'

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3



flutter:
  uses-material-design: true
